name: Handle New Issues

on:
  issues:
    types:
      - opened

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add Triage Label
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: "Status: Triage"
